version: "3.8"
services:
  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWD:-secret}
    ports:
      - 127.0.0.1:${DB_PORT:-5432}:5432

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server

  celery:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
      - redis
    environment:
      DEBUG: 0
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWD:-secret}@db:5432/${DB_NAME:-db}
      # CELERY_BROKER_URL: redis://redis:6379/0
      # CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: sh start_celery.sh

  api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - staticfiles:/usr/src/app/staticfiles/
      - media:/usr/src/app/media/
    depends_on:
      - db
    environment:
      DEBUG: 0
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWD:-secret}@db:5432/${DB_NAME:-db}
    ports:
      - 127.0.0.1:${LOCAL_PORT:-8000}:8000
    command: sh start_web.sh

volumes:
  dbdata:
  staticfiles:
  media:
