# Generated by Django 5.0.4 on 2024-05-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
