name: Testing CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ruff
        run: |
          pip install ruff

      - name: Run ruff
        run: |
          ruff check .

      - name: Install coverage
        run: |
          pip install coverage

      - name: Run tests
        run: coverage run -m pytest

      - name: Fail if coverage is below 80%
        run: |
          coverage report --fail-under=80
